server:
  applicationConnectors:
    - type: http
      port: 5002
  rootPath: /bff/*
  requestLog:
    appenders:
      - type: console
        # Jersey request log format see https://logback.qos.ch/manual/layouts.html#AccessPatternLayout
        # We would like to include the correlation-id here as well, but the logback-access module does not support it:
        # https://jira.qos.ch/browse/LOGBACK-1016
        logFormat: '{ "status": "%s", "uri": "%U", "request": "%U%q", "request_method": "%m", "request_time": "%elapsedTime", "body_bytes_sent": "%b", "http_referrer": "%header{Referer}", "http_user_agent": "%replace(%header{User-Agent}){"\"", ""}", "http_x_forwarded_proto": "%header{X-Forwarded-Proto}", "http_x_forwarded_for": "%replace(%header{X-Forwarded-For}){"[0-9]{1,3}$", "xxx"}" }'

logging:
  level: WARN
  loggers:
    de.demiway.bonus.backend: INFO
    io.dropwizard: INFO
    org.hibernate.validator: ERROR
  appenders:
    - type: console
      # Application log format see https://logback.qos.ch/manual/layouts.html
      logFormat: '{ "level": "%level", "class": "%c", "text": "%replace(%replace(%msg%ex{30}){"[\r\n]", "\\n\\t"}){"[\"\t]", ""}", "CorrelationID": "%mdc{correlation-id}" }%nopex%n'


environment:
  isLocal: ${IS_LOCAL:-false}
  cognitoDomain: ${COGNITO_DOMAIN:-}
  allowLocalhostOrigin: ${ALLOW_LOCALHOST_ORIGIN:-false}

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the JDBC URL
  url: <doesntMatter>

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
